### ISSUE TITLE
Fish - Animation Sprite

### ISSUE THREAD

**Issue by Psypher9** [astro-panda/ldjam-51#15]
- When moving in the water area the fish looks like a fish swimming

- when on a platform in the air area the fish looks like a fish flopping on the ground with small hops

- when _moving_ in the air area the fish looks like a fish flopping around

**Comment by BadgerBeeC137** [comment]
![fishNormal](https://user-images.githubusercontent.com/114771759/193477212-baee9f01-7ada-4948-9375-64e764f0895b.png)
![fishSquash](https://user-images.githubusercontent.com/114771759/193477217-6bafad39-903a-4092-9d08-2b1dd8873d41.png)
![fishStretch](https://user-images.githubusercontent.com/114771759/193477220-dd646199-1298-4d46-a5cd-e5b61f9a0e0f.png)
![fishSwim](https://user-images.githubusercontent.com/114771759/193477222-2fc2ab79-6ad8-4453-bce7-4e6383ddfaba.png)
