### ISSUE TITLE
Fish - Carry Items Sprites

### ISSUE THREAD

**Issue by Psypher9** [astro-panda/ldjam-51#17]
There are animated sprites for the following fish states:

- Carrying a screw
- Carrying a wrench

**Comment by BadgerBeeC137** [comment]
![fishSwimScrew](https://user-images.githubusercontent.com/114771759/193478077-cbe050f1-fe0c-4ed0-9efa-4f2462e956f1.png)
![fishNormalScrew](https://user-images.githubusercontent.com/114771759/193478079-1f390267-7667-4483-b45e-38980d8ef7f4.png)

**Comment by BadgerBeeC137** [comment]
![fishNormalWrench](https://user-images.githubusercontent.com/114771759/193479705-d91e1c29-22ea-4d44-82c6-d98cb9a693e9.png)
![fishSwimWrench](https://user-images.githubusercontent.com/114771759/193479707-9913931a-647a-4cda-8528-2cfae09285b1.png)
