### ISSUE TITLE
Collectibles - Sprites

### ISSUE THREAD

**Issue by Psypher9** [astro-panda/ldjam-51#19]
There are sprites for the following objects

- Screw
- Wrench

**Comment by BadgerBeeC137** [comment]
![Screw](https://user-images.githubusercontent.com/114771759/193478041-d602c238-c4bc-4dca-b7af-8a70a886de60.png)
![Wrench](https://user-images.githubusercontent.com/114771759/193478043-3cd14018-5b6a-4f5d-9383-18b3573fd156.png)
