### ISSUE TITLE
Main - Octopus and Mech

### ISSUE THREAD

**Issue by Psypher9** [astro-panda/ldjam-51#26]
There is a section of the main scene, in the water area where I can see

- an octopus working on a mech

**Comment by BadgerBeeC137** [comment]
![octoWrench](https://user-images.githubusercontent.com/114771759/193481055-8aa89b36-155a-4e25-a247-d5ef99393d6a.png)
![octoIdle1](https://user-images.githubusercontent.com/114771759/193481056-e7f08f31-1865-4ab4-a85c-98eae0075ef3.png)
![octoIdle2](https://user-images.githubusercontent.com/114771759/193481058-b423f91c-48dd-46a8-a28e-970b7b2b7863.png)
